int globalVariable;
float globalVariable2;

void main(){
    int localVariable = 1;
    float localVariable2 = 2.0;
    globalVariable = 5;
    globalVariable2 = 8.0;
    printf("=");
    printf("localVariable = %i", localVariable);
    printf("localVariable2 = %f", localVariable2);
    printf("globalVariable = %i", globalVariable);
    printf("globalVariable2 = %f", globalVariable2);
    printf("");
    localVariable++;
    localVariable2++;
    globalVariable++;
    globalVariable2++;
    printf("++");
    printf("localVariable = %i", localVariable);
    printf("localVariable2 = %f", localVariable2);
    printf("globalVariable = %i", globalVariable);
    printf("globalVariable2 = %f", globalVariable2);
    printf("");
    localVariable--;
    localVariable2--;
    globalVariable--;
    globalVariable2--;
    printf("--");
    printf("localVariable = %i", localVariable);
    printf("localVariable2 = %f", localVariable2);
    printf("globalVariable = %i", globalVariable);
    printf("globalVariable2 = %f", globalVariable2);
    printf("");
    localVariable += 4;
    localVariable2 += 4;
    globalVariable += 4;
    globalVariable2 += 4;
    printf("+= 4");
    printf("localVariable = %i", localVariable);
    printf("localVariable2 = %f", localVariable2);
    printf("globalVariable = %i", globalVariable);
    printf("globalVariable2 = %f", globalVariable2);
    printf("");
    localVariable -= 4;
    localVariable2 -= 4;
    globalVariable -= 4;
    globalVariable2 -= 4;
    printf("-= 4");
    printf("localVariable = %i", localVariable);
    printf("localVariable2 = %f", localVariable2);
    printf("globalVariable = %i", globalVariable);
    printf("globalVariable2 = %f", globalVariable2);
    printf("");
    localVariable *= 4;
    localVariable2 *= 4;
    globalVariable *= 4;
    globalVariable2 *= 4;
    printf("*= 4");
    printf("localVariable = %i", localVariable);
    printf("localVariable2 = %f", localVariable2);
    printf("globalVariable = %i", globalVariable);
    printf("globalVariable2 = %f", globalVariable2);
    printf("");
    localVariable /= 4;
    localVariable2 /= 4;
    globalVariable /= 4;
    globalVariable2 /= 4;
    printf("/= 4");
    printf("localVariable = %i", localVariable);
    printf("localVariable2 = %f", localVariable2);
    printf("globalVariable = %i", globalVariable);
    printf("globalVariable2 = %f", globalVariable2);
}